# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Upvotes',
            new_name='Upvote',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='answers',
            new_name='answer',
        ),
    ]
