# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0010_remove_upvote_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
