# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0011_upvote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='vote',
        ),
    ]
